id: PARALLELAUTOMATION
parent_id: TECH
name: 并行自动化
disabled: False
search_only: False
category: TECH
sort_string: 并行自动化
content_container:
- contents:
  - widget_type: CodexText
    text: <link="PARALLELAUTOMATION">并行自动化</link>
    style: Title
  - widget_type: CodexDividerLine
  layout: Vertical
- contents:
  - widget_type: CodexText
    text: 在不大的空间中实现多线自动化。
    style: Body
  - widget_type: CodexSpacer
  layout: Vertical
- contents:
  - widget_type: CodexText
    text: 前提技术
    style: Subtitle
  - widget_type: CodexDividerLine
  - widget_type: CodexSpacer
  - widget_type: CodexText
    text: <link="GENERICSENSORS">通用传感器</link>
    style: Body
  - widget_type: CodexSpacer
  layout: Vertical
- contents:
  - widget_type: CodexText
    text: 解锁
    style: Subtitle
  - widget_type: CodexDividerLine
  - widget_type: CodexSpacer
  layout: Vertical
- contents:
  - widget_type: CodexImage
    image: logic_ribbon_0__ui
  - widget_type: CodexText
    text: <link="LOGICRIBBON">信号线组</link>
    style: Body
  layout: Horizontal
- contents:
  - widget_type: CodexImage
    image: logic_ribbon_bridge_0__ui
  - widget_type: CodexText
    text: <link="LOGICRIBBON">信号线组桥</link>
    style: Body
  layout: Horizontal
- contents:
  - widget_type: CodexImage
    image: logic_ribbon_writer_0__ui
  - widget_type: CodexText
    text: <link="LOGICRIBBONWRITER">线组写入器</link>
    style: Body
  layout: Horizontal
- contents:
  - widget_type: CodexImage
    image: logic_ribbon_reader_0__ui
  - widget_type: CodexText
    text: <link="LOGICRIBBONREADER">线组读取器</link>
    style: Body
  layout: Horizontal
