name: Pull Request Action
on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.TOKEN_FOR_FORMAT_BOT }}
          fetch-depth: 0
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: '23.2'
          elixir-version: '1.11.2'
      - run: |
          mix deps.get
          mix format
      - id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - if: steps.git-check.outputs.modified == 'true'
        run: |
          git config user.name ${{ github.event.pull_request.user.login }}
          git config user.email github.action@onicn.com
          git add .
          git commit -m "code format"
          git push
